

@startuml Meu Diagram

header Subscription Platform Acceptance Test
title "Creating a Postpaid Subscription to High-Income Plan"
footer powered by Almerindo Rehem

!$COLOR_SUCCESS = "#green"
!$COLOR_ERROR = "#red"

!$FONT_COLOR = "<font color=pink>"


participant serviceA $COLOR_ERROR
participant serviceB #FFA000

serviceA [$COLOR_ERROR]->x serviceB
activate serviceA

loop#Gold #LightGoldenRodYellow while XPTO > 0

serviceB -->x serviceA

serviceA -> serviceB : SYNC 
serviceB [$COLOR_SUCCESS]--> serviceA: SYNC

note left
 {:xpto 2}
end note

deactivate serviceA

end loop

serviceA ->> serviceB ++: ASYNC
serviceB -->> serviceA --: ASYNC

@enduml